
import { PERMISSIONS, PermissionValue } from '@/auth/permissions';
import { ROLE_PERMISSIONS } from '@/auth/rbac/roles';

// Re-export central permissions as admin-specific types
export const ADMIN_PERMISSIONS = {
  // Admin dashboard access
  ADMIN_ACCESS: PERMISSIONS.ADMIN.ACCESS,
  ADMIN_VIEW: PERMISSIONS.ADMIN.VIEW,
  ADMIN_EDIT: PERMISSIONS.ADMIN.EDIT,
  
  // User management 
  USERS_VIEW: PERMISSIONS.USERS.VIEW,
  USERS_CREATE: PERMISSIONS.USERS.CREATE,
  USERS_EDIT: PERMISSIONS.USERS.EDIT,
  USERS_DELETE: PERMISSIONS.USERS.DELETE,
  
  // Content management
  CONTENT_VIEW: PERMISSIONS.CONTENT.VIEW,
  CONTENT_CREATE: PERMISSIONS.CONTENT.CREATE,
  CONTENT_EDIT: PERMISSIONS.CONTENT.EDIT,
  CONTENT_DELETE: PERMISSIONS.CONTENT.DELETE,
  CONTENT_PUBLISH: PERMISSIONS.CONTENT.PUBLISH,
  
  // Build management
  BUILDS_VIEW: PERMISSIONS.BUILDS_VIEW,
  BUILDS_CREATE: PERMISSIONS.BUILDS_CREATE,
  BUILDS_EDIT: PERMISSIONS.BUILDS_EDIT,
  BUILDS_APPROVE: PERMISSIONS.BUILDS_APPROVE,
  
  // Settings management
  SETTINGS_VIEW: PERMISSIONS.SETTINGS.VIEW,
  SETTINGS_EDIT: PERMISSIONS.SETTINGS.EDIT,
  
  // System management
  SYSTEM_VIEW: PERMISSIONS.SYSTEM.VIEW,
  SYSTEM_SETTINGS: PERMISSIONS.SYSTEM.SETTINGS,
  SYSTEM_LOGS: PERMISSIONS.SYSTEM.LOGS,
  SYSTEM_RESTART: PERMISSIONS.SYSTEM.RESTART,
  
  // Add missing permissions
  THEMES_VIEW: PERMISSIONS.THEMES_VIEW,
  THEMES_EDIT: PERMISSIONS.THEMES_EDIT,
  THEMES_DELETE: PERMISSIONS.THEMES_DELETE,
  
  DATA_VIEW: PERMISSIONS.DATA_VIEW,
  DATA_EDIT: PERMISSIONS.DATA_EDIT,
  DATA_IMPORT: PERMISSIONS.DATA_IMPORT,
  DATA_EXPORT: PERMISSIONS.DATA_EXPORT,
  
  ANALYTICS_VIEW: PERMISSIONS.ANALYTICS_VIEW,
  
  // Super admin
  SUPER_ADMIN: PERMISSIONS.SUPER_ADMIN
} as const;

// Type for admin permission values
export type AdminPermissionValue = PermissionValue;

// Re-export the role permissions mapping
export { ROLE_PERMISSIONS } from '@/auth/rbac/roles';
