
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const autoImportsPath = resolve(__dirname, '../auto-imports.d.ts');

// Simple template for an empty auto-imports file
const template = `// This file is auto-generated by unplugin-auto-import
// Do not modify this file directly.

// @ts-nocheck
export {}
declare global {
  // global variables would be placed here
}
`;

try {
  // Write the template to the file
  fs.writeFileSync(autoImportsPath, template, 'utf8');
  console.log('Successfully cleared auto-imports.d.ts file.');
  console.log('Please rebuild your project to generate new auto-imports.');
} catch (error) {
  console.error('Error clearing auto-imports.d.ts file:', error);
}
