
/**
 * This script clears the auto-imports.d.ts file to fix syntax errors.
 * Run this script when you encounter auto-import related errors.
 */
import fs from 'fs';
import path from 'path';

const autoImportsPath = path.resolve(__dirname, '../src/auto-imports.d.ts');

// Simple template for an empty auto-imports file
const template = `// This file is auto-generated by unplugin-auto-import
// Do not modify this file directly.

// @ts-nocheck
export {}
declare global {

}
`;

try {
  // Write the template to the file
  fs.writeFileSync(autoImportsPath, template, 'utf8');
  console.log('Successfully cleared auto-imports.d.ts file.');
  console.log('Please rebuild your project to generate new auto-imports.');
} catch (error) {
  console.error('Error clearing auto-imports.d.ts file:', error);
}
