// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzfeiosaptgbkejmpmdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZmVpb3NhcHRnYmtlam1wbWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTU0NTgsImV4cCI6MjA1OTEzMTQ1OH0.ihibuPTPJReE1PVK5H5gcycimjDIf6Lhr0Z0PDXnn6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);