
// This file is automatically generated. Do not edit it directly.
import { supabase as appSupabase } from '@/chat/lib/supabase';

// Re-export the chat module's supabase client
export const supabase = appSupabase;

// For typing purposes
export type Database = any;
