
import { UserRole } from './types/roles';

// Define permission values
export const PERMISSIONS = {
  MANAGE_USERS: 'manage_users',
  VIEW_USERS: 'view_users',
  EDIT_USERS: 'edit_users',
  DELETE_USERS: 'delete_users',
  
  MANAGE_CONTENT: 'manage_content',
  VIEW_CONTENT: 'view_content',
  EDIT_CONTENT: 'edit_content',
  DELETE_CONTENT: 'delete_content',
  
  MANAGE_SETTINGS: 'manage_settings',
  VIEW_SETTINGS: 'view_settings',
  EDIT_SETTINGS: 'edit_settings',
  
  MANAGE_THEMES: 'manage_themes',
  VIEW_THEMES: 'view_themes',
  EDIT_THEMES: 'edit_themes',
  DELETE_THEMES: 'delete_themes',
  
  MANAGE_ADMIN: 'manage_admin',
  ACCESS_ADMIN: 'access_admin',
  
  SYSTEM_DEBUG: 'system_debug'
} as const;

// Create a union type of all permission values
export type PermissionValue = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Define role-based permissions
export const ROLE_PERMISSIONS: Record<UserRole, PermissionValue[]> = {
  super_admin: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.VIEW_CONTENT,
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.DELETE_CONTENT,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.MANAGE_THEMES,
    PERMISSIONS.VIEW_THEMES,
    PERMISSIONS.EDIT_THEMES,
    PERMISSIONS.DELETE_THEMES,
    PERMISSIONS.MANAGE_ADMIN,
    PERMISSIONS.ACCESS_ADMIN,
    PERMISSIONS.SYSTEM_DEBUG
  ],
  
  admin: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.VIEW_CONTENT,
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.DELETE_CONTENT,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.VIEW_THEMES,
    PERMISSIONS.EDIT_THEMES,
    PERMISSIONS.ACCESS_ADMIN
  ],
  
  moderator: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_CONTENT,
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.ACCESS_ADMIN
  ],
  
  editor: [
    PERMISSIONS.VIEW_CONTENT,
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.ACCESS_ADMIN
  ],
  
  user: []
};
